blueprint:
  name: Automatic air conditioner for winter and summer, monitoring presence, window status, water level and time slot.
  description:  "`- Version: 1.0 -`\n\n This blueprint is for using the air conditioner automatically in both winter and summer, based on a start and end temperature. 

          Optionally, you can enable:
          - Home presence control 
          - Notifications
          - Decide on the time slot for operation"

  domain: automation
  input:

    climate:
      name: Entities climate
      description: 'Select climate entities to be used.'
      selector:
        entity:
          domain: climate

    season:
      name: Select season
      description: 'Select the season of use.'
      default: Summer
      selector:
        select:
          mode: dropdown
          options:
            - Summer
            - Winter

    set_temperature_climate:
      name: Set temperature climate
      default: 25
      description: 'Select the temperature to be set at climate.'
      selector:
        number:
          min: 15
          max: 30
          unit_of_measurement: °C
          mode: slider
          step: 1

    hvac_modes:
      name: Hvac modes
      description: 'Select the mode to be set to the air conditioner.'
      default: dry
      selector:
        select:
          mode: dropdown
          options:
            - heat
            - cool
            - dry
            - fan_only

    fan_modes:
      name: Fan modes
      description: 'Select the ventilation speed to be set at the air conditioner.'
      default: auto
      selector:
        select:
          mode: dropdown
          options:
            - auto
            - high
            - low
            - mid

    presence_home:
      name: Presence Home
      description: 'Select the group consisting of person.'
      default: input_boolean.presence_home_disabled
      selector:
        entity:
          domain: input_boolean

    target_temperature_start:
      name: Target temperature start
      default: 25
      description: 'Set the startup target temperature.'
      selector:
        number:
          min: 15
          max: 30
          unit_of_measurement: °C
          mode: slider
          step: 1

    target_temperature_stop:
      name: Target temperature stop
      default: 21
      description: 'Set the target temperature for shutdown.'
      selector:
        number:
          min: 15
          max: 30
          unit_of_measurement: °C
          mode: slider
          step: 1

    delay_temperature_stop:
      default: 10
      name: Delay temperature stop
      description: 'Set the climate shutdown delay since the target temperature has been reached.'
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: min
          mode: slider
          step: 1

    start_time:
      name: Start time
      default: "00:00:00"
      description: 'Set automatic operation start time.'
      selector:
        time: 

    stop_time:
      name: Stop time
      default: "00:00:00"
      description: 'Set automatic operation end time.'
      selector:
        time: 

    notify_device:
      name: Device to notify push
      default: false
      description: 'Device needs to run the official Home Assistant app to receive notifications.'
      selector:
        device: 
          integration: mobile_app

mode: parallel
variables:
  season: !input season
  target_temperature_start: !input target_temperature_start
  climate: !input climate
  target_temperature_stop: !input target_temperature_stop
  presence_home: !input presence_home

trigger:
- platform: numeric_state
  entity_id: !input climate
  attribute: current_temperature
  above: !input target_temperature_start
  id: climate_on
- platform: numeric_state 
  entity_id: !input climate
  attribute: current_temperature 
  below: !input target_temperature_start
  id: climate_on
- platform: numeric_state
  entity_id: !input climate
  attribute: current_temperature 
  below: !input target_temperature_stop
  for: 
    minutes: !input delay_temperature_stop
  id: climate_off
- platform: numeric_state
  entity_id: !input climate
  attribute: current_temperature 
  above: !input target_temperature_stop
  for: 
    minutes: !input delay_temperature_stop
  id: climate_off
- platform: time
  at: !input stop_time
  id: climate_off
- platform: time
  at: !input start_time
  id: climate_on
- platform: state
  entity_id: !input presence_home
  from: 
      - off
      - on
  to: 
      - off
      - on
  id: presence_home

action:
- alias: Turn on air conditioner
  if:
    - "{{is_state(climate,'off')}}"
    - condition: time
      after: !input start_time
      before: !input stop_time
    - "{{ states(presence_home) == 'on' or presence_home == 'group.presence_home_disabled'}}"
    - or: 
      - "{{ (trigger.id == 'climate_on' or (trigger.id == 'presence_home' and trigger.to_state.state == 'on')) and season == 'Winter' and (state_attr(climate,'current_temperature')|float(0) < target_temperature_start|float(0) )}}"
      - "{{ (trigger.id == 'climate_on' or (trigger.id == 'presence_home' and trigger.to_state.state == 'on')) and season == 'Summer' and (state_attr(climate,'current_temperature')|float(0) > target_temperature_start|float(0) )}}"
  then:
      - alias: Kontrola obecnosci w domu
        if: 
          - " {{ presence_home == 'binary_sensor.presence_home_disabled' or states(presence_home) == 'on'}}"
        then: 
          - service: climate.set_temperature
            data:
              entity_id: !input climate
              temperature: !input set_temperature_climate
              hvac_mode: !input hvac_modes
          - delay: 
              seconds: 1
          - service: climate.set_fan_mode
            data:
              entity_id: !input climate
              fan_mode: !input fan_modes
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "KLIMATYZACJA"
            message: "Automatyczne włącznie klimatyzacji przy temperaturze: {{state_attr(climate,'current_temperature')|float(0)}}°"
        else:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "KLIMATYZACJA"
            message: "Klimatyzacja nie włączona bo nikogo nie ma w domu."
- alias: Turn off air conditioner
  if: 
    - "{{not is_state(climate,'off')}}"
    - or: 
      - "{{ trigger.id == 'presence_home' and trigger.to_state.state == 'off'}}"
      - "{{ trigger.id == 'climate_off' and season == 'Winter' and (state_attr(climate,'current_temperature')|float(0) > target_temperature_stop|float(0) )}}"
      - "{{ trigger.id == 'climate_off' and season == 'Summer' and (state_attr(climate,'current_temperature')|float(0) < target_temperature_stop|float(0) )}}"
      - "{{ trigger.id == 'climate_off' and trigger.platform == 'time'}}"
  then:
      - service: climate.turn_off
        target:
          entity_id: !input climate
      - domain: mobile_app
        type: notify
        device_id: !input notify_device
        title: "KLIMATYZACJA"
        message: "{% if (trigger.id == 'climate_off' or trigger.id == 'presence_home')%} Automatyczne wyłączenie klimatyzacji{% endif %}"
          
